name: VirtualSensorsDockerImage

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -f virtual-sensors/Dockerfile -t virtual-sensors:$(date +%s) .
